global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "nginx"
    static_configs:
      - targets: ["nginx:80"]
    
  - job_name: "postgres"
    static_configs:
      - targets: ["postgres:5432"]